Repository Team-A-Mango/A-Mango-Client, pull requests merged in 2024-12, with the labels that each got.

#7 메인 페이지 퍼블리싱 진행
  src/app/page.tsx
  src/assets/png/Banner.png
  src/assets/png/TestImg.png
  src/assets/svg/footerLogo.tsx
  src/assets/svg/index.tsx
  src/components/common/footer/index.tsx
  src/components/main/atoms/GoodsListItem/index.tsx
  src/components/main/atoms/GoodsListItem/style.ts
  src/components/main/molecules/GoodsList/index.tsx
  src/components/main/molecules/GoodsList/style.ts
  src/components/main/organisms/MainWrapper/index.tsx
  src/components/main/organisms/MainWrapper/style.ts
Labels: 🎨 Type: Publishing

#9 프로필 컴포넌트 제작
  src/assets/svg/Mango.tsx
  src/assets/svg/Setting.tsx
  src/assets/svg/Wave.tsx
  src/assets/svg/index.tsx
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
Labels: ✨ Type: Feature

#12 상품 등록 페이지 제작
  src/app/(page)/sell/page.tsx
  src/assets/icons/Picture.tsx
  src/assets/icons/index.tsx
  src/assets/svg/MangoMini.tsx
  src/assets/svg/index.tsx
  src/components/sell/atoms/ImageInput/index.tsx
  src/components/sell/atoms/Logo/index.tsx
  src/components/sell/atoms/TypeText/index.tsx
  src/components/sell/molecules/SellForm/index.tsx
  src/components/sell/molecules/SellForm/style.ts
  src/components/sell/organisms/SellWrapper/index.tsx
  src/components/sell/organisms/SellWrapper/style.ts
Labels: 🎨 Type: Publishing

#13 svg를 카맬 케이스로 변경
  src/app/(page)/hand-sign/page.tsx
  src/assets/svg/CallSign.tsx
  src/assets/svg/OkSign.tsx
  src/assets/svg/PeaceSign.tsx
  src/assets/svg/RockSign.tsx
  src/assets/svg/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
  src/components/hand-sign/atoms/Caution/index.tsx
  src/components/hand-sign/atoms/HandSign/index.tsx
  src/components/hand-sign/atoms/Title/index.tsx
  src/components/hand-sign/molecules/HandSIgnContainer/index.tsx
  src/components/hand-sign/organisms/HandSignWrapper/index.tsx
  src/components/hand-sign/organisms/HandSignWrapper/style.ts
Labels: ⚡Type: Simple

#14 🔀인스턴스 추가
  .gitignore
  src/api/axios.ts
Labels: ✨ Type: Feature

#21 🔀 찜 기능 구현
  src/assets/svg/AfterLike.tsx
  src/assets/svg/BeforeLike.tsx
  src/components/goods-detail/organisms/GoodsDetailContainer/index.tsx
  src/components/goods-detail/organisms/GoodsDetailContainer/style.ts
Labels: ✨ Type: Feature

#24 🔀 상품삭제 기능 추가
  src/assets/svg/AfterLike.tsx
  src/assets/svg/Like.tsx
  src/assets/svg/index.tsx
  src/components/common/Button/index.tsx
  src/components/goods-detail/molecules/PriceContainer/index.tsx
  src/components/goods-detail/molecules/PriceContainer/style.ts
  src/components/goods-detail/organisms/GoodsDetailContainer/index.tsx
Labels: ✨ Type: Feature

#25 add header routing
  src/assets/svg/Person.tsx
  src/assets/svg/Plus.tsx
  src/assets/svg/Shopping.tsx
  src/assets/svg/index.tsx
  src/components/Header/index.tsx
  src/components/Header/style.ts
Labels: ✨ Type: Feature
